apiVersion: v1
kind: Pod
metadata:
  name: deimos
  labels:
    app: deimos
    monitor: 'true'
spec:
  containers:
  - name: deimos
    image: pangealab/deimos:latest
    env:
      - name: INSTANCE_URL
        value: $INSTANCE_URL
      - name: MID_USERNAME
        value: $MID_USERNAME
      - name: MID_PASSWORD
        value: $MID_PASSWORD
      - name: MID_NAME
        value: $MID_NAME